#! /usr/bin/env Rscript

# File description -------------------------------------------------------------
#
# This script loads the data generated by exper.R and
# saves the resulting plots in a directory specified by the earlier
# experiment parameterization file. It requires as an argument the
# path to that experiment parameterization file, and is expected to be
# run from the boot_expers/ directory.
#
# Example call:
# Rscript vis/vis_exper.R /scratch/users/kriss1/working/boot_expers/expers/exper_d20_n20.json

## ---- setup ----
args <- commandArgs(trailingOnly=TRUE) # give paths for experiment json
library("jsonlite")
library("feather")
library("plyr")
library("dplyr")
library("ggplot2")
library("ggtern")
library("reshape2")
library("FactoMineR")

# minimal theme for ggplots
theme_set(theme_bw())
min_theme <- theme_update(
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.ticks = element_blank(),
  legend.title = element_text(size = 8),
  legend.text = element_text(size = 6),
  axis.text = element_text(size = 6),
  axis.title = element_text(size = 8),
  strip.background = element_blank(),
  strip.text = element_text(size = 8),
  legend.key = element_blank()
)

source("vis/vis_utils.R")
exper <- fromJSON(args[[1]])

## ---- read-output ----
paths <- exper$paths
output_dir <- file.path(paths$base, paths$output_dir)
plot_dir <- file.path(paths$base, paths$plot_dir)
beta <- output_dir %>%
  list.files("beta_boot_[0-9]+", full.names = TRUE) %>%
  combine_replicates()
colnames(beta)[3] <- "k"
theta <- output_dir %>%
  list.files("theta_boot_[0-9]+", full.names = TRUE) %>%
  combine_replicates()

## ---- theta-benchmarks ----
theta_truth <- file.path(paths$base, paths$params, "theta.feather") %>%
  read_feather()
theta_truth$n <- seq_len(nrow(theta_truth))
theta_truth <- theta_truth %>%
  melt(measure.vars = c("V1", "V2"), variable.name = "k")
theta_truth$k <- as.integer(gsub("V", "", theta_truth$k))

theta_fit <- output_dir %>%
  list.files("theta_hat_vb", full.names = TRUE) %>%
  read_feather()

## ---- beta-benchmarks ----
beta_truth <- file.path(paths$base, paths$params, "beta.feather") %>%
  read_feather()
beta_truth$k <- seq_len(nrow(beta_truth))

mbeta_truth <- beta_truth %>%
  melt(id.vars = "k", variable.name = "v")
mbeta_truth$v <- gsub("V", "", mbeta_truth$v)

beta_fit <- output_dir %>%
  list.files("beta_hat_vb", full.names = TRUE) %>%
  read_feather()

beta_fit <- beta_fit %>%
  mutate(k = Var2) %>%
  select(-Var2) %>%
  melt(id.vars = "k", variable.name = "v")

## ---- process-beta ----
mbeta <- beta %>%
  melt(
    id.vars = c("file", "rep", "k"),
    variable.name = "v"
  )

v_order <- mbeta %>%
  group_by(v) %>%
  summarise(mean = max(value)) %>%
  arrange(desc(mean)) %>%
  select(v) %>%
  unlist()

mbeta$v <- factor(mbeta$v, levels = v_order)
mbeta_truth$v <- factor(mbeta_truth$v, levels = v_order)
beta_fit$v <- factor(beta_fit$v, levels = v_order)

## ---- process-theta ----
n_order <- theta_truth %>%
  group_by(n) %>%
  summarise(entropy = -mean(value * log(value))) %>%
  arrange(entropy) %>%
  select(n) %>%
  unlist()

theta$n <- factor(theta$n, levels = n_order)
theta_truth$n <- factor(theta_truth$n, levels = n_order)
theta_fit$n <- factor(theta_fit$n, levels = n_order)

## ---- alignment-approach ----
R <- max(mbeta$rep)
beta_fit_mat <- beta_fit %>%
  dcast(k ~ v) %>%
  select(-k) %>%
  as.matrix()

pi <- match_matrices(mbeta[, c("rep", "k", "v", "value")], beta_fit_mat)
mbeta$k <- pi$pi_row

## ---- visualize-aligned ----
beta_plot(
  list("samples" = mbeta, "truth" = mbeta_truth, "fit" = beta_fit),
  aligned = TRUE
) %>%
  ggsave(file = file.path(plot_dir, "beta_aligned.pdf"))

## ---- align-theta ----
for (i in seq_len(R)) {
  print_skip(i)
  cur_pi <- pi[which(pi$rep == i), "pi_row"]
  for (j in seq_along(cur_pi)) {
    theta[which(theta$rep == i & theta$k == j), "k"] <- cur_pi[j]
  }
}

theta_plot(
  list("samples" = theta, "truth" = theta_truth, "fit" = theta_fit),
  aligned = TRUE
) %>%
  ggsave(file = file.path(plot_dir, "theta_aligned.pdf"))

## ---- vb-samples-beta ----
beta_samples <- file.path(output_dir, "beta_samples_vb.feather") %>%
  read_feather()
colnames(beta_samples) <- c("rep", "k", "v", "value")
beta_samples$v <- factor(beta_samples$v, levels = v_order)

pi <- match_matrices(
  beta_samples,
  beta_truth %>%
    select(-k) %>%
    as.matrix()
)

beta_samples$k <- pi$pi_row

beta_plot(
  list("samples" = beta_samples, "truth" = mbeta_truth),
  aligned = TRUE
) %>%
  ggsave(file = file.path(plot_dir, "beta_vb.pdf"))

## ---- vb-samples-theta ----
theta_samples <- file.path(output_dir, "theta_samples_vb.feather") %>%
  read_feather()
colnames(theta_samples) <- c("rep", "n", "k", "theta")

for (i in seq_len(R)) {
  print_skip(i)
  cur_pi <- pi[which(pi$rep == i), "pi_row"]
  for (j in seq_along(cur_pi)) {
    theta[which(theta$rep == i & theta$k == j), "k"] <- cur_pi[j]
  }
}

theta_plot(
  list("samples" = theta, "truth" = theta_truth),
  aligned = TRUE
) %>%
  ggsave(file = file.path(plot_dir, "theta_vb.pdf"))

## ---- gibbs-samples-beta ----
beta_samples <- file.path(output_dir, "beta_samples_gibbs.feather") %>%
  read_feather()
colnames(beta_samples) <- c("rep", "k", "v", "value")
pi <- match_matrices(
  beta_samples,
  beta_truth %>%
    select(-k) %>%
    as.matrix()
)

beta_samples$k <- pi$pi_row
beta_samples$v <- factor(beta_samples$v, levels = v_order)

beta_plot(
  list("samples" = beta_samples, "truth" = mbeta_truth),
  aligned = TRUE
) %>%
  ggsave(file = file.path(plot_dir, "beta_gibbs.pdf"))

## ---- gibbs-samples-thtea ----
theta_samples <- file.path(output_dir, "theta_samples_gibbs.feather") %>%
  read_feather()
colnames(theta_samples) <- c("rep", "n", "k", "theta")

for (i in seq_len(R)) {
  print_skip(i)
  cur_pi <- pi[which(pi$rep == i), "pi_row"]
  for (j in seq_along(cur_pi)) {
    theta_samples[which(theta_samples$rep == i & theta_samples$k == j), "k"] <- cur_pi[j]
  }
}

theta_plot(
  list("samples" = theta_samples, "truth" = theta_truth),
  aligned = TRUE
) %>%
  ggsave(file = file.path(plot_dir, "theta_gibbs.pdf"))


## ---- tours ----
projs <- combn(exper$model$V, 3)
class(projs) <- "character"

p_beta <- mbeta %>%
  select(-file) %>%
  dcast(k + rep ~ v)

for (i in seq_len(10)) {
  simplex_proj(p_beta, projs[, i]) %>%
    ggsave(file = file.path(plot_dir, paste0("simplex_proj_", i, ".pdf")), device = NULL)
}

## ---- correspondence-analysis ----
p_beta_fit <- beta_fit %>%
  dcast(k ~ v) %>%
  as.matrix()

p_beta_truth <- mbeta_truth %>%
  dcast(k ~ v) %>%
  as.matrix()

p_beta <- rbind(
  data.frame(type = "bootstrap", p_beta %>% select(-rep)),
  data.frame(type = "fit", p_beta_fit),
  data.frame(type = "truth", p_beta_truth)
)

ca_beta <- CA(p_beta %>% select(-type, -k))
beta_row_coords <- data.frame(
  type = p_beta$type,
  k = p_beta$k,
  ca_beta$row$coord
)

p <- ggplot() +
  geom_point(data = beta_row_coords %>% filter(type == "bootstrap"),
             aes(x = Dim.1, y = Dim.2, shape = type, col = as.factor(k)),
             size = .5, alpha = 0.5) +
  geom_point(data = beta_row_coords %>% filter(type != "bootstrap"),
             aes(x = Dim.1, y = Dim.2, shape = type, col = as.factor(k))) +
  scale_color_brewer(palette = "Set2") +
  coord_fixed()
ggsave(p, file = file.path(plot_dir, "correspondence_analysis.pdf"))
