#! /usr/bin/env Rscript

# File description -------------------------------------------------------------
#
# This script loads the data generated by exper.R and reshapes it for
# easier plotting in vis_expers.R. It saves a few tangential plots in
# a directory specified by the earlier experiment parameterization
# file. It requires as an argument the path to that experiment
# parameterization file, and is expected to be run from the
# boot_expers/ directory.
#
# Example call:
# Rscript vis/vis_exper.R /scratch/users/kriss1/working/boot_expers/expers/exper_d20_n20.json

## ---- setup ----
args <- commandArgs(trailingOnly=TRUE) # give paths for experiment json
library("jsonlite")
library("feather")
library("plyr")
library("dplyr")
library("ggplot2")
library("ggtern")
library("reshape2")
library("FactoMineR")

# minimal theme for ggplots
theme_set(theme_bw())
min_theme <- theme_update(
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.ticks = element_blank(),
  legend.title = element_text(size = 8),
  legend.text = element_text(size = 6),
  axis.text = element_text(size = 6),
  axis.title = element_text(size = 8),
  strip.background = element_blank(),
  strip.text = element_text(size = 8),
  legend.key = element_blank()
)

source("vis/vis_utils.R")
exper <- fromJSON(args[[1]])
paths <- exper$paths
output_dir <- file.path(paths$base, paths$output_dir)
plot_dir <- file.path(paths$base, paths$plot_dir)

###############################################################################
# First, we read in the true / fitted parameters from LDA and assure
# the clusters are aligned. This is completely removed from the
# bootstrapping and sampling data we look at later.
###############################################################################

## ---- theta-benchmarks ----
theta_truth <- file.path(paths$base, paths$params, "theta.feather") %>%
  read_feather()
theta_truth$n <- seq_len(nrow(theta_truth))
theta_truth <- theta_truth %>%
  melt(id.vars = "n", variable.name = "k", value.name = "theta")
theta_truth$k <- as.integer(gsub("V", "", theta_truth$k))

theta_fit <- output_dir %>%
  list.files("theta_hat_vb", full.names = TRUE) %>%
  read_feather()

# align fitted and true theta clusters
pi <- match_matrix(
  theta_fit %>%
    dcast(k ~ n) %>%
    select(-k) %>%
    as.matrix(),
  theta_truth %>%
    dcast(k ~ n) %>%
    select(-k) %>%
    as.matrix()
)

theta_old <- theta_fit
for (i in seq_along(pi)) {
  theta_fit[theta_old$k == pi[i], "k"] <- unique(theta_truth$k)[i]
}

## ---- beta-benchmarks ----
beta_fit <- output_dir %>%
  list.files("beta_hat_vb", full.names = TRUE) %>%
  read_feather()
beta_truth <- file.path(paths$base, paths$params, "beta.feather") %>%
  read_feather()

pi <- match_matrix(
  beta_fit %>%
    select(-Var2) %>%
    as.matrix(),
  as.matrix(beta_truth)
)

beta_truth$k <- seq_len(nrow(beta_truth))
beta_fit$k <- beta_fit$Var2[pi]
beta_fit$Var2 <- NULL

mbeta_truth <- beta_truth %>%
  melt(id.vars = "k", variable.name = "v")
mbeta_truth$v <- gsub("V", "", mbeta_truth$v)

beta_fit <- beta_fit %>%
  melt(id.vars = "k", variable.name = "v")

###############################################################################
# Next, we read in the bootstrap samples and ensure they are aligned
# with the cluster labels set above.
###############################################################################

## ---- read-output ----
beta <- output_dir %>%
  list.files("beta_boot_[0-9]+", full.names = TRUE) %>%
  combine_replicates()
colnames(beta)[3] <- "k"
theta <- output_dir %>%
  list.files("theta_boot_[0-9]+", full.names = TRUE) %>%
  combine_replicates()

## ---- process-beta ----
mbeta <- beta %>%
  melt(
    id.vars = c("file", "rep", "k"),
    variable.name = "v"
  )

v_order <- mbeta %>%
  group_by(v) %>%
  summarise(mean = max(value)) %>%
  arrange(desc(mean)) %>%
  select(v) %>%
  unlist()

mbeta$v <- factor(mbeta$v, levels = v_order)
mbeta_truth$v <- factor(mbeta_truth$v, levels = v_order)
beta_fit$v <- factor(beta_fit$v, levels = v_order)

## ---- process-theta ----
n_order <- theta_truth %>%
  group_by(n) %>%
  summarise(entropy = -mean(theta * log(theta))) %>%
  arrange(entropy) %>%
  select(n) %>%
  unlist()

theta$n <- factor(theta$n, levels = n_order)
theta_truth$n <- factor(theta_truth$n, levels = n_order)
theta_fit$n <- factor(theta_fit$n, levels = n_order)

## ---- alignment-approach ----
R <- max(mbeta$rep)
beta_fit_mat <- beta_fit %>%
  dcast(k ~ v) %>%
  select(-k) %>%
  as.matrix()

pi <- match_matrices(mbeta[, -1], beta_fit_mat)
mbeta$k <- pi$pi_row

theta <- pi %>%
  mutate(k = row) %>%
  select(-row, -pi_ix) %>%
  right_join(theta) %>%
  mutate(k = pi_row) %>%
  select(-pi_row)

###############################################################################
# We can use the same logic for processing the variational bayes and
# gibbs samples.
###############################################################################

## ---- vb-samples-beta ----
beta_samples_vb <- file.path(output_dir, "beta_samples_vb.feather") %>%
  read_feather()
colnames(beta_samples_vb) <- c("rep", "k", "v", "value")
R <- max(beta_samples_vb$rep)

pi <- match_matrices(
  beta_samples_vb,
  beta_truth %>%
    select(-k) %>%
    as.matrix()
)

beta_samples_vb$k <- pi$pi_row
beta_samples_vb$v <- factor(beta_samples_vb$v, levels = v_order)

## ---- vb-samples-theta ----
theta_samples_vb <- file.path(output_dir, "theta_samples_vb.feather") %>%
  read_feather()
colnames(theta_samples_vb) <- c("rep", "n", "k", "theta")
theta_samples_vb$n <- factor(theta_samples_vb$n, levels = n_order)

theta_samples_vb <- pi %>%
  mutate(k = row) %>%
  select(-row, -pi_ix) %>%
  right_join(theta_samples_vb) %>%
  mutate(k = pi_row) %>%
  select(-pi_row)

## ---- gibbs-samples-beta ----
beta_samples_gibbs <- file.path(output_dir, "beta_samples_gibbs.feather") %>%
  read_feather()
colnames(beta_samples_gibbs) <- c("rep", "k", "v", "value")
R <- max(beta_samples_gibbs$rep)
pi <- match_matrices(
  beta_samples_gibbs,
  beta_truth %>%
    select(-k) %>%
    as.matrix()
)

beta_samples_gibbs$k <- pi$pi_row
beta_samples_gibbs$v <- factor(beta_samples_gibbs$v, levels = v_order)

## ---- gibbs-samples-theta ----
theta_samples_gibbs <- file.path(output_dir, "theta_samples_gibbs.feather") %>%
  read_feather()
colnames(theta_samples_gibbs) <- c("rep", "n", "k", "theta")
theta_samples_gibbs$n <- factor(theta_samples_gibbs$n, levels = n_order)

theta_samples_gibbs <- pi %>%
  mutate(k = row) %>%
  select(-row, -pi_ix) %>%
  right_join(theta_samples_gibbs) %>%
  mutate(k = pi_row) %>%
  select(-pi_row)

###############################################################################
# To facilitate simpler plotting across the methods, we merge them into a
# single frame and write the results to file.
###############################################################################

## ---- write-results ----
theta_merged <- rbind(
  theta_samples_gibbs %>%
    mutate(method = "gibbs") %>%
    cbind(data.frame(paths$base, exper$model)),
  theta_samples_vb %>%
    mutate(method = "vb") %>%
    cbind(data.frame(paths$base, exper$model)),
  theta %>%
    mutate(method = "bootstrap") %>%
    select(-file) %>%
    cbind(data.frame(paths$base, exper$model)),
  theta_truth %>%
    mutate(method = "truth", rep = "1") %>%
    cbind(data.frame(paths$base, exper$model)),
  theta_fit %>%
    mutate(method = "vb_fit", rep = "1") %>%
    cbind(data.frame(paths$base, exper$model))
)

write_feather(
  theta_merged,
  file.path(output_dir, "theta_merged.feather")
)

beta_merged <- rbind(
  beta_samples_gibbs %>%
    mutate(method = "gibbs") %>%
    cbind(data.frame(paths$base, exper$model)),
  beta_samples_vb %>%
    mutate(method = "vb") %>%
    cbind(data.frame(paths$base, exper$model)),
  mbeta %>%
    mutate(method = "bootstrap") %>%
    select(-file) %>%
    cbind(data.frame(paths$base, exper$model)),
  mbeta_truth %>%
    mutate(method = "truth", rep = "1") %>%
    cbind(data.frame(paths$base, exper$model)),
  beta_fit %>%
    mutate(method = "vb_fit", rep = "1") %>%
    cbind(data.frame(paths$base, exper$model))
)

write_feather(
  beta_merged,
  file.path(output_dir, "beta_merged.feather")
)

###############################################################################
# We consider some correspondence analysis and simplex views as supplements,
# but they are not the main focus of this script.
###############################################################################

## ---- tours ----
projs <- combn(exper$model$V, 3)
class(projs) <- "character"

p_beta <- mbeta %>%
  select(-file) %>%
  dcast(k + rep ~ v)

for (i in seq_len(10)) {
  simplex_proj(p_beta, projs[, i]) %>%
    ggsave(file = file.path(plot_dir, paste0("simplex_proj_", i, ".pdf")), device = NULL)
}

## ---- correspondence-analysis ----
p_beta_fit <- beta_fit %>%
  dcast(k ~ v) %>%
  as.matrix()

p_beta_truth <- mbeta_truth %>%
  dcast(k ~ v) %>%
  as.matrix()

p_beta <- rbind(
  data.frame(type = "bootstrap", p_beta %>% select(-rep)),
  data.frame(type = "fit", p_beta_fit),
  data.frame(type = "truth", p_beta_truth)
)

ca_beta <- CA(p_beta %>% select(-type, -k))
beta_row_coords <- data.frame(
  type = p_beta$type,
  k = p_beta$k,
  ca_beta$row$coord
)

p <- ggplot() +
  geom_point(data = beta_row_coords %>% filter(type == "bootstrap"),
             aes(x = Dim.1, y = Dim.2, shape = type, col = as.factor(k)),
             size = .5, alpha = 0.5) +
  geom_point(data = beta_row_coords %>% filter(type != "bootstrap"),
             aes(x = Dim.1, y = Dim.2, shape = type, col = as.factor(k))) +
  scale_color_brewer(palette = "Set2") +
  coord_fixed()
ggsave(p, file = file.path(plot_dir, "correspondence_analysis.pdf"))
