#! /usr/bin/env Rscript

# File description -------------------------------------------------------------
#
# This script loads the data generated by vis_data.R and
# creates corresponding figures.

## ---- setup ----

# Setup packages ---------------------------------------------------------------
library("ggplot2")
library("scales")
library("plyr")
library("dplyr")
library("reshape2")

# minimal theme for ggplots
theme_set(theme_bw())
min_theme <- theme_update(
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.ticks = element_blank(),
  legend.title = element_text(size = 8),
  legend.text = element_text(size = 6),
  axis.text = element_text(size = 4.5),
  axis.title = element_text(size = 8),
  strip.background = element_blank(),
  strip.text = element_text(size = 4.5),
  legend.key = element_blank()
)

# Code Block -------------------------------------------------------------------
## ---- read-data ----
theta <- list()
beta <- list()
theta[[1]] <- read_feather("figure/d100_n20/theta_merged.feather")
theta[[2]] <- read_feather("figure/d100_n100/theta_merged.feather")
beta[[1]] <- read_feather("figure/d100_n20/beta_merged.feather")
beta[[2]] <- read_feather("figure/d100_n100/beta_merged.feather")

theta <- do.call(rbind, theta)
beta <- do.call(rbind, beta)

# theta plot
theta_supp <- theta %>%
  filter(method %in% c("truth")) %>%
  mutate(type = method) %>%
  select(-method)
theta <- theta %>%
  filter(!(method %in% c("truth", "vb_fit")))

## ---- thetasmallnlargedisc ----
ggplot() +
  geom_histogram(data = theta %>% filter(N == 20, as.numeric(n) < 20),
                 aes(x = theta, fill = as.factor(k)),
                 position = "identity", alpha = 0.8, binwidth = 0.01) +
  geom_vline(data = theta_supp %>% filter(as.numeric(n) < 20),
             aes(xintercept = theta, col = as.factor(k))) +
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  scale_y_continuous(expand = c(0, 0), breaks = pretty_breaks(n = 1)) +
  facet_grid(n ~ method, scale = "free_y") +
  labs(fill = "cluster", col = "cluster") +
  ggtitle("Posterior thetas [large discrepancies, small n(i)]")

## ---- thetasmallnsmalldisc ----
ggplot() +
  geom_histogram(data = theta %>% filter(N == 20, as.numeric(n) > 80),
                 aes(x = theta, fill = as.factor(k)),
                 position = "identity", alpha = 0.8, binwidth = 0.01) +

  geom_vline(data = theta_supp %>% filter(as.numeric(n) > 80),
             aes(xintercept = theta, col = as.factor(k))) +
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  scale_y_continuous(expand = c(0, 0), breaks = pretty_breaks(n = 1)) +
  facet_grid(n ~ method, scale = "free_y") +
  labs(fill = "cluster", col = "cluster") +
  ggtitle("Posterior Thetas [small discrepancies, small n(i)]")

## ---- thetalargenlargedisc ----
ggplot() +
  geom_histogram(data = theta %>% filter(N == 100, as.numeric(n) < 20),
                 aes(x = theta, fill = as.factor(k)),
                 position = "identity", alpha = 0.8, binwidth = 0.01) +
  geom_vline(data = theta_supp %>% filter(as.numeric(n) < 20),
             aes(xintercept = theta, col = as.factor(k))) +
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  scale_y_continuous(expand = c(0, 0), breaks = pretty_breaks(n = 1)) +
  facet_grid(n ~ method, scale = "free_y") +
  labs(fill = "cluster", col = "cluster") +
  ggtitle("Posterior Thetas [large discrepancies, large n(i)]")

## ---- thetalargensmalldisc ----
ggplot() +
  geom_histogram(data = theta %>% filter(N == 100, as.numeric(n) > 80),
                 aes(x = theta, fill = as.factor(k)),
                 position = "identity", alpha = 0.8, binwidth = 0.01) +
  geom_vline(data = theta_supp %>% filter(as.numeric(n) > 80),
             aes(xintercept = theta, col = as.factor(k))) +
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  scale_y_continuous(expand = c(0, 0), breaks = pretty_breaks(n = 1)) +
  facet_grid(n ~ method, scale = "free_y") +
  labs(fill = "cluster", col = "cluster") +
  ggtitle("Posterior thetas [small discrepancies, large n(i)]")

## ---- prepare-beta ----
beta_supp <- beta %>%
  filter(method %in% c("truth")) %>%
  mutate(type = method) %>%
  select(-method)
beta <- beta %>%
  filter(!(method %in% c("truth", "vb_fit", "vb_mean")))

## ---- betasmalln ----
ggplot() +
  geom_vline(data = beta_supp, aes(xintercept = value, col = as.factor(k)),
             size = 0.2) +
  geom_histogram(data = beta %>% filter(N == 20),
                 aes(x = value, fill = as.factor(k)),
                 binwidth = .01) +
  geom_hline(yintercept = 0, size = 0.1, col = "#696969") +
  geom_vline(xintercept = 0, size = 0.3, col = "#696969") +
  scale_y_continuous(expand = c(0, 0), breaks = scales::pretty_breaks(n = 2)) +
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  facet_grid(method ~ v) +
  coord_flip() +
  theme(
    axis.text.x = element_blank(),
    panel.spacing = unit(0, "line")
  ) +
  labs(fill = "cluster", col = "cluster") +
  ggtitle("Posterior Betas [small n(i)]")

## ---- betalargen ----
ggplot() +
  geom_vline(data = beta_supp, aes(xintercept = value, col = as.factor(k)),
             size = 0.2) +
  geom_histogram(data = beta %>% filter(N == 100),
                 aes(x = value, fill = as.factor(k)),
                 binwidth = .003) +
  geom_hline(yintercept = 0, size = 0.1, col = "#696969") +
  geom_vline(xintercept = 0, size = 0.3, col = "#696969") +
  scale_y_continuous(expand = c(0, 0), breaks = scales::pretty_breaks(n = 2)) +
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  facet_grid(method ~ v) +
  coord_flip() +
  theme(
    axis.text.x = element_blank(),
    panel.spacing = unit(0, "line")
  ) +
  labs(fill = "cluster", col = "cluster") +
  ggtitle("Posterior Betas [large n(i)]")
